---
### Create configuration files for Junos devices on local basis
### Must be executed only if local structure has been created with playbook: playbook-ztp-init.yml
- name: Check status of Junos devices
  hosts: devices
  connection: local
  gather_facts: yes
  vars:
    - jsnapy_test: "{{role_path}}/files/jsnapy.yaml"
    - netconf:
        host:{{ junos_host }}
        username:{{ansible_ssh_user}}
        password:{{ansible_ssh_pass}}

  roles:
    - {role: junos-check}
