---
### Setup Local directory structure to store files locally
- name: Init ZTP directory strucutre to store local files
  hosts: ztp-servers
  connection: local
  gather_facts: no
  vars_files:
    - "group_vars/ztp-servers/ztp.yaml"
  roles:
    - {role: ztp-init}

### Create configuration files locally
- name: Populate local ZTP configurations
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - "group_vars/ztp-servers/ztp.yaml"
  roles:
    - {role: ztp-create-config}
