---
### Setup Local directory structure to store files locally
- name: Init ZTP directory strucutre to store local files
  hosts: ansible-servers
  connection: local
  gather_facts: no
  vars_files:
    - "group_vars/ansible-servers/ztp-init.yaml"
  roles:
    - {role: ztp-init}
