---
### Create configuration files for Junos devices on local basis
### Must be executed only if local structure has been created with playbook: playbook-ztp-init.yml
- name: Populate local deivces configuration
  hosts: devices
  connection: local
  gather_facts: no
  vars_files:
      - "group_vars/all/ztp-variables.yaml"
  roles:
    - {role: junos-conf-generator}
