global:
    root_hash: $1$ZUlES4dp$OUwWo1g7cLoV/aMWpHUnC/
    login_message: This is the property of Example Corp. Do not login without express permission.
    time_zone: Europe/Paris
    mgmt_sub_mask: 24
    name_servers:
    - 192.168.5.68
    - 192.168.60.131
    ntp_servers:
    - 172.17.28.5
    snmp:
        location: "Site 1"
        contact: John Doe
        polling:
        - community: public
    routes:
      static:
          172.0.0.0/8: 10.94.194.254
